# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae1ffce968b7b22ff042cb10eb671f021a760c55b2e6196d4f58f315b64f7892f285ca429cf79b76952902bbe24fb86ab3984ab942cdde58943048de3de42492

test:
  secret_key_base: 140b893b98304931776d129d1e44dfadde0a0883898251b6b7b254170827097f183f85bf6210b39281452b2047f795d63e97fd4c6b35b84ce524fced20e899a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
